//! Attribution generator for the Sivana handoff.
//!
//! Groups exported tracks by license and emits human-readable credit lines.
//! This is a legal-safety artifact, not just documentation — Sivana's
//! distribution story depends on it being accurate.

use anyhow::Result;
use arachne_core::models::TrackRecord;
use std::collections::BTreeMap;
use std::io::Write as _;
use std::path::Path;

/// Write attribution.txt grouped by license.
pub fn write_attribution(tracks: &[TrackRecord], path: &Path) -> Result<()> {
    let mut by_license: BTreeMap<&str, Vec<&TrackRecord>> = BTreeMap::new();
    for t in tracks {
        by_license.entry(t.license.as_str()).or_default().push(t);
    }

    let file = std::fs::File::create(path)?;
    let mut w = std::io::BufWriter::new(file);

    writeln!(w, "ATTRIBUTION")?;
    writeln!(w, "===========")?;
    writeln!(
        w,
        "Generated by Arachne {} from source '{}'.",
        env!("CARGO_PKG_VERSION"),
        tracks
            .first()
            .map(|t| t.source.as_str())
            .unwrap_or("unknown")
    )?;
    writeln!(w)?;
    writeln!(
        w,
        "Each track below is credited with its title, artist, source identifier,"
    )?;
    writeln!(
        w,
        "and origin URL. License terms are grouped at the end of this file."
    )?;
    writeln!(w)?;

    for (license, group) in &by_license {
        writeln!(w, "== License: {license} ({} tracks) ==", group.len())?;
        for t in group {
            let title = t.title.as_deref().unwrap_or("(untitled)");
            let artist = t.artist.as_deref().unwrap_or("(unknown artist)");
            writeln!(w, "- {title} — {artist}")?;
            if let Some(album) = &t.album {
                writeln!(w, "  Album: {album}")?;
            }
            writeln!(w, "  Source: {} id={}", t.source, t.source_id)?;
            writeln!(w, "  URL: {}", t.url)?;
        }
        writeln!(w)?;
    }

    Ok(())
}
