[package]
name = "arachne-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
thiserror = "1.0.61"
figment = { version = "0.10.19", features = ["toml", "env"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
bincode = "1.3.3"
toml = "0.8.14"
psl = "2.1.18"
url = "2.5.2"
chrono = { version = "0.4.38", features = ["serde"] }
uuid = { version = "1.8.0", features = ["serde", "v4"] }
async-nats = "0.35.0"
scylla = "0.13.0"
sqlx = { workspace = true }
futures = "0.3.30"
tokio = { version = "1.38.0", features = ["full"] }
texting_robots = "0.2.1"
reqwest = { version = "0.12.5", features = ["json"] }
dashmap = "6.0.1"
governor = "0.6.3"
bloomfilter = "1.0.14"
prometheus = "0.13.4"
axum = "0.7.5"
once_cell = "1.19.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "json"] }
scraper = "0.19.0"
object_store = { version = "0.11", features = ["aws"] }
bytes = "1"
sha2 = "0.10"
hex = "0.4"
infer = "0.16"
lofty = "0.21"
fs4 = { version = "0.12", features = ["tokio"] }
quick-xml = "0.36"
feed-rs = "2.2"
regex = "1"
